# Generated by Django 4.1.7 on 2023-03-25 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250)),
                ('category', models.CharField(choices=[('ACCO', 'ACCOMPAGNEMENT'), ('PLAT', 'PLAT'), ('DESS', 'DESSERT'), ('BOIS', 'BOISSON')], max_length=4)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
                ('recipe_img', models.ImageField(upload_to='Image/')),
                ('ingredient', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Ingredient')),
                ('instruction', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Instruction')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('time_cook', models.CharField(max_length=10)),
                ('temps_cuisson', models.CharField(max_length=10)),
                ('num_people', models.CharField(max_length=10)),
                ('level', models.CharField(choices=[('F', 'FACILE'), ('M', 'MOYENNE'), ('D', 'DIFFICILE')], max_length=2)),
                ('rate', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
