# Generated by Django 4.1.7 on 2023-03-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('ACCO', 'Accompagnement'), ('PLAT', 'PLat'), ('DESS', 'Dessert'), ('BOIS', 'Boisson')], max_length=4),
        ),
    ]
